Anas dev v2
tutorinedutech/tutorin-backend pull request #26
Opened 2024-06-11 08:48 UTC by khairunas001

1. ubah config jadi https
2. tambah fitur user untuk melihat profile sendiri pada route `"/tutors/my-profile-tutor"` dan `"/tutors/my-profile-learner"`
3. perubahan pada `.env`

```
#database
DATABASE_URL = "mysql://root:@localhost:3306/tutorin"

# Google Cloud Storageprod
GOOGLE_PROJECT_ID = 
GOOGLE_APPLICATION_CREDENTIALS = 
GOOGLE_BUCKET_NAME = 

#token signing key
JWT_SECRET= 

# midtrans
MIDTRANS_PUBLIC_API = https://api.sandbox.midtrans.com
MIDTRANS_SERVER_KEY =
MIDTRANS_CLIENT_KEY = 

# https
SSL_KEY_PATH = server.key
SSL_CERT_PATH = server.cert

#untukdevelompent
# NODE_ENV = developments

#untukproduction
NODE_ENV = production
```

4. untuk mendapatkan `server.key` dan `server.cert` perlu menguntsall openssl pada os, setelah ini menjalankan cli `openssl req -nodes -new -x509 -keyout server.key -out server.cert` untuk mengenerate keynya.

2024-06-11 11:23 UTC, haidarmaula commented on src/handlers/showUserProfile/learnerProfileHandler.js
> +      where: { id: learnerId },
ini ngambil data tutor berdasarkan learnerId?

2024-06-11 11:29 UTC, haidarmaula requested changes
Udah oke sih, cuma ubah nama rute aja anas biar konsisten.
1. `tutors/{tutorId}/profile` buat nampilin halaman profil tutor untuk diri dia sendiri
2. `tutors/{tutorId}/search` buat nampilin halaman profil tutor untuk diliat sama learner

2024-06-11 11:29 UTC, haidarmaula commented on src/handlers/showUserProfile/learnerProfileHandler.js
> +      where: { id: learnerId },
ini ngambil data tutor berdasarkan learnerId?

2024-06-11 11:29 UTC, haidarmaula commented on src/routes.js
> +    path: '/tutors/my-profile-tutor',
`/tutors/{tutorId}/profile`

2024-06-11 11:29 UTC, haidarmaula commented on src/routes.js
> +    path: '/tutors/my-profile-learner',
`/tutors/{tutorId}/search`

2024-06-11 12:19 UTC, khairunas001 commented on src/handlers/showUserProfile/learnerProfileHandler.js
> +      where: { id: learnerId },
kan emang buat nampilin data learner kan?

2024-06-12 07:12 UTC, tutorinedutech approved these changes

2024-06-12 07:13 UTC, haidarmaula approved these changes

2024-06-12 07:13 UTC, merged